name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  MY_GENDER:
    description: "Gender"
    required: true
    default: "Female"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "bell"
  color: "green"
